name: Feature request
description: Describes a functional requirement
labels: ["enhancement | 新功能需求"]
title: "[Feature]: "

body:
  - type: textarea
    id: feature-request
    attributes:
      label: Desired function
      description: Please describe the new features you need
    validations:
      required: true
